---
- name: install docker
  package:
    name: docker

- name: enable and start docker
  systemd: name=docker state=started enabled=yes

- name: Install docker-compose
  get_url: 
    url : https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'